apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-gnbsim
  labels:
    app: f5gc-gnbsim
    # sliceidx: 6d3d79da-f781-4cd9-813a-dbdad01e01c0
  annotations:
    free5gc.org/nssi-id: '27394d25-dbf5-428e-8fc3-f5b2add67115'
    free5gc.org/nsi-ids: '[
        { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" },
    ]'
    free5gc.org/supported-snssais: '[
        { "st": 1,
          "ssd": "010203",
        },
        { "st": 1,
          "ssd": "112233",
        },
    ]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-gnbsim
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: f5gc-gnbsim
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{
            "name": "n1n2",
            "namespace": "default",
            "interface": "net1",
            "ip": "172.16.20.10"
          },
          {
            "name": "n3",
            "namespace": "default",
            "interface": "net3",
            "ip": "192.168.10.10"
          }]'
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: free5g-304-gnbsim 
          image: psethi/free5g-304-gnbsim:dev 
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Always
          command: ["sh"]
          tty: true
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]
          volumeMounts:
            - mountPath: /dev/net/tun
              name: tun-devdir
          ports:
            - containerPort: 2152
              name: if-n3
              protocol: UDP
        - name: f5gc-gnbsim-probe
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http-probe
              protocol: TCP
        - name: tcpdump
          image: corfr/tcpdump
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: f5gc-gnbsim-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tun-devdir
          hostPath:
            path: /dev/net/tun

